### Test 1: Register a new user (POST /api/auth/register/)
POST http://192.168.1.247:8000/api/auth/register/
Content-Type: application/json

{
    "username": "rojogpt2",
    "email": "rojogpt2@gmail.com",
    "password": "password123"
}

###

### Test 2: Login to get JWT token (POST /api/auth/login/)
POST https://622c-102-18-13-98.ngrok-free.app/api/auth/login/
Content-Type: application/json

{
    "username": "rojogpt1",
    "password": "password123"
}
###

### Test 3: Get user profile (GET /api/auth/profile/) with JWT
GET https://622c-102-18-13-98.ngrok-free.app/api/auth/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNzUxNDcyLCJpYXQiOjE3NDE3NDc4NzIsImp0aSI6ImVjMTgxYWU5MTc3MTQ4ZGQ5NTcwNDljNWYwMDk4N2E1IiwidXNlcl9pZCI6M30.q1kurHDuWE1YEtCsZVFn2UNRCkKoCQh-pQzKywdONBg
Content-Type: application/json

###

### Test 4: Logout (POST /api/auth/logout/) with JWT
POST https://622c-102-18-13-98.ngrok-free.app/api/auth/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxNzUxNDcyLCJpYXQiOjE3NDE3NDc4NzIsImp0aSI6ImVjMTgxYWU5MTc3MTQ4ZGQ5NTcwNDljNWYwMDk4N2E1IiwidXNlcl9pZCI6M30.q1kurHDuWE1YEtCsZVFn2UNRCkKoCQh-pQzKywdONBg
Content-Type: application/json

###

### Test 5: Reset Password (POST /api/auth/reset-password/)
POST https://622c-102-18-13-98.ngrok-free.app/api/auth/reset-password/
Content-Type: application/json

{
    "email": "rojogpt1@gmail.com"
}
### Test 6: Login to get JWT token with new password(POST /api/auth/login/)
POST https://622c-102-18-13-98.ngrok-free.app/api/auth/login/
Content-Type: application/json

{
    "username": "rojogpt1",
    "password": "newpassword123"
}
###