# Generated by Django 5.1.6 on 2025-03-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.CharField(max_length=512)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
