# Generated by Django 5.1.6 on 2025-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='response_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='user_request',
            field=models.TextField(),
        ),
    ]
